name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-varsion: [17.x]

    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm install
      - name: Build project
        if: always()
        run: npm run build:prod
      - name: Lint code
        if: always()
        run: npm run lint:ts
      - name: Lint scss
        if: always()
        run: npm run lint:scss
      - name: Unit testing
        if: always()
        run: npm run test:unit
      - name: Build storybook
        if: always()
        run: npm run storybook:build
      - name: Snapshot testing
        if: always()
        run: npm run test:ui:ci
